{"uuid": "a7087240-5ab5-4a0c-9187-7d6c4df8e6a6", "children": ["334621c1-a15f-4a92-83ce-c8d9600d4fa9"], "befores": [{"name": "register_and_remove_user", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stellarburgers.nomoreparties.site', port=443): Max retries exceeded with url: /api/auth/register (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x106a2aed0>: Failed to resolve 'stellarburgers.nomoreparties.site' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "trace": "  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/Desktop/Diplom/Diplom_2/conftest.py\", line 17, in register_and_remove_user\n    user_registration_response = Api.register_user(data.User.new_user_data)\n                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/Desktop/Diplom/Diplom_2/api.py\", line 11, in register_user\n    return requests.post(f'{locators.Urls.URL}{locators.Urls.REGISTER_USER}',\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "steps": [{"name": "Отправить запрос на регистрацию пользователя", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stellarburgers.nomoreparties.site', port=443): Max retries exceeded with url: /api/auth/register (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x106a2aed0>: Failed to resolve 'stellarburgers.nomoreparties.site' ([Errno 8] nodename nor servname provided, or not known)\"))\n", "trace": "  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/Desktop/Diplom/Diplom_2/api.py\", line 11, in register_user\n    return requests.post(f'{locators.Urls.URL}{locators.Urls.REGISTER_USER}',\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/api.py\", line 115, in post\n    return request(\"post\", url, data=data, json=json, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/jobanyjrot/PycharmProjects/DiplomaDemo/.venv/lib/python3.12/site-packages/requests/adapters.py\", line 700, in send\n    raise ConnectionError(e, request=request)\n"}, "parameters": [{"name": "body", "value": "{'email': 'jennifer26@example.net', 'password': 'vWY9)rk1)3', 'name': 'megan33'}"}], "start": 1729247572582, "stop": 1729247572584}], "start": 1729247572582, "stop": 1729247572584}], "start": 1729247572582, "stop": 1729247572632}